# Site meta
title: Digital Archives
description: >- # this means to ignore newlines until "baseurl:"
  This site documents policies and procedures of the NYPL Digital Archives program, which manages the
  born-digital portions of archival acquisitions by the 11 curatorial units of the NYPL Research Libraries.
url: "https://nypl.github.io"
baseurl: "/digarch"

# Build settings
# theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs
search_enabled: true
search_tokenizer_separator: /[\s/]+/
heading_anchors: true
#color_scheme: "dark"
